### ISSUE TITLE
Users are able to reach "set icon for predefined links" (but cant really set the icon)

### ISSUE THREAD

**Issue by ZzyzxIsAlreadyTaken** [Adam-it/TilesLinksForSPOnline#30] opened 2022-12-20 09:09 UTC
**Describe the bug**
The web part lets me try to set icons for admin predefined links, but it obviously does not work as it then would have to write back to the admin list and that would set the icon for everyone. 

**To Reproduce**
1. Add web part to page
2. Add a predefined link
3. Add predefined link to web part 
4. Hover over predefined link and edit it
5. Click on set icon in the property pane
6. Close the property pane
7. No icon has been added

**Expected behavior**
Remove edit from predefined links for users
Add icon support in predefined links list for admins (it might work, pending reply from Adam if the functionality is there)

**Screenshots**
![image](https://user-images.githubusercontent.com/18461079/208627419-7c9a9115-87e8-458c-803f-ec9bf76b215e.png)

**Comment by Adam-it** [comment] 2022-12-20 21:46
I checked that and actually, it works like this by design and as I checked it worked properly. 
So the links in the admin site are just predefined links the user may use to add his or her own personal link. When such a link it added its definition is actually copied to the user's personal links json file stored in the user Apps folder OneDrive. So it is actually a copy not connected in any way to the SharePoint list. After that, the user is able to edit this link in any way: change title, URL and icon, as this is his or her personal link.

as for 

>Add icon support in predefined links list for admins (it might work, pending reply from Adam if the functionality is there)

I think this may be done maybe with some list formating magic but no in any easy way and please open a separate idea/feature issue for it 👍.

**Comment by Adam-it** [comment] 2022-12-20 21:59
I recorded a movie how it works on my side on a test env I created to recheck this webpart. 
As you may see seems to be working as described and properly

https://user-images.githubusercontent.com/58668583/208774777-5a21fe8d-5922-4791-b709-1b9c6bcc19f5.mp4

**Comment by Adam-it** [comment] 2022-12-20 21:59
closing as this behavior is by design

**Closed by Adam-it** 2022-12-20 21:59 UTC
Labels: to investigate, work in progress
